/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsinurida;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nury
 */
public class KelolaApp extends javax.swing.JFrame {

    public TblData data = null;
    private JFileChooser jfc;
    private File file;
    private Image image;
    private String[] Kata;
    private String str;
    KoneksiDB connection = new KoneksiDB();

    /**
     * Creates new form KelolaApp
     */
    public KelolaApp() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_HORIZ); 
        setVisible(true);
        setResizable(false);
        autonomor();
    }

    public void itemTerpilih(String nama, String konst, String tipe, String var){
        TblData data = new TblData();
        data.tampilkandata();
        TFNamaKel.setText(nama);
        TFKonstKel.setText(konst);
        TFTipeKel.setText(tipe);
        TFVarKel.setText(var);
        LblFoto.setIcon(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LblFoto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NamaAppKel1 = new javax.swing.JLabel();
        NamaAppKel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        KonstAppKel = new javax.swing.JLabel();
        TipeAppKel = new javax.swing.JLabel();
        VarAppKel = new javax.swing.JLabel();
        BtnSimpan = new javax.swing.JButton();
        SoalAppKel = new javax.swing.JLabel();
        TAKel = new java.awt.TextArea();
        TFno = new javax.swing.JTextField();
        TFNamaKel = new javax.swing.JTextField();
        TFKonstKel = new javax.swing.JTextField();
        TFTipeKel = new javax.swing.JTextField();
        TFVarKel = new javax.swing.JTextField();
        BtnImage = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CBKelas = new javax.swing.JComboBox();
        BtnEdit = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(750, 550));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("Kelola Soal & Jawaban");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setText("Identitas Jawaban");

        NamaAppKel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        NamaAppKel1.setText("ID");

        NamaAppKel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        NamaAppKel.setText("Nama Program");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setText("Deklarasi");

        KonstAppKel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        KonstAppKel.setText("Konstanta");

        TipeAppKel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        TipeAppKel.setText("Tipe Data");

        VarAppKel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        VarAppKel.setText("Variabel");

        BtnSimpan.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        SoalAppKel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        SoalAppKel.setText("Soal Algoritma");

        TAKel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        TAKel.setName(""); // NOI18N
        TAKel.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                TAKelTextValueChanged(evt);
            }
        });
        TAKel.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TAKelInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        TFno.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        TFno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnoActionPerformed(evt);
            }
        });

        TFNamaKel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        TFNamaKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNamaKelActionPerformed(evt);
            }
        });

        TFKonstKel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        TFKonstKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFKonstKelActionPerformed(evt);
            }
        });

        TFTipeKel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        TFTipeKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTipeKelActionPerformed(evt);
            }
        });

        TFVarKel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        TFVarKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFVarKelActionPerformed(evt);
            }
        });

        BtnImage.setText("Browse Img");
        BtnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImageActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel5.setText("Klasifikasi");

        CBKelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Runtunan", "Pemilihan", "Pengulangan", "Runtunan & Pemilihan", "Runtunan & Pengulangan", "Pemilihan & Pengulangan", "Runtunan & Pemilihan & Pengulangan" }));

        BtnEdit.setText("Edit");
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        BtnBatal.setText("Batal");
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SoalAppKel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnImage))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TAKel, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(BtnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(379, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NamaAppKel)
                                .addComponent(NamaAppKel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(TFno, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(TFNamaKel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TipeAppKel)
                                .addComponent(KonstAppKel)
                                .addComponent(VarAppKel))
                            .addGap(31, 31, 31)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TFKonstKel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TFTipeKel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TFVarKel, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(CBKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel2)))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnImage)
                                .addGap(212, 212, 212))
                            .addComponent(LblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(SoalAppKel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NamaAppKel1)
                            .addComponent(TFno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NamaAppKel)
                            .addComponent(TFNamaKel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CBKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFKonstKel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KonstAppKel))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipeAppKel)
                            .addComponent(TFTipeKel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VarAppKel)
                            .addComponent(TFVarKel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(BtnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBatal))
                    .addComponent(TAKel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void autonomor(){
     String sql = "select max(id) from appdb";
     try{
         Statement statement = connection.getKoneksi().createStatement();
         ResultSet resultset = statement.executeQuery(sql);
         while (resultset.next()){
             int nmr = resultset.getInt(1);
             TFno.setText(""+ Integer.toString(nmr+1));
         }
     }catch (Exception e){
         System.out.println(""+ e.getMessage());
     }
 }
 
 public void tokenisasi(){
      String Kalimat;
        Kalimat = TAKel.getText().toLowerCase()
        .replace("!", " ").replace("@", " ").replace("#", " ")
        .replace("$", " ").replace("%", " ").replace("^", " ")
        .replace("&", " ").replace("*", " ").replace("(", " ")
        .replace(")", " ").replace("-", " ").replace("_", " ")
        .replace("=", " ").replace("+", " ").replace("{", " ")
        .replace("[", " ").replace("}", " ").replace("]", " ")
        .replace(";", " ").replace(":", " ").replace("'", " ")
        .replace(",", " ").replace("<", " ").replace(".", " ")
        .replace(">", " ").replace("/", " ").replace("?", " ")
        .replace("~", " ").replace("`", " ")
        .replaceAll("0", " ").replaceAll("1", " ")
        .replaceAll("2", " ").replaceAll("3", " ")
        .replaceAll("4", " ").replaceAll("5", " ")
        .replaceAll("6", " ").replaceAll("7", " ")
        .replaceAll("8", " ").replaceAll("9", " ")
        .replaceAll("\\n+", " ").replaceAll("\\s+", " ").replaceAll("\\t+", " ");
     Kata = Kalimat.split(" ");
 }
 
 public String filter(String str) throws SQLException{
     tokenisasi();
     ArrayList<String> wordsList = new ArrayList<>();
     String[] stopwords = new String[2000];
     String sCurrentLine;
     int k=0;
     FileReader fr = null;
     try {
         fr = new FileReader("D:\\stopwords_id.txt");
     } catch (FileNotFoundException ex) {
         Logger.getLogger(KelolaApp.class.getName()).log(Level.SEVERE, null, ex);
     }
     
     BufferedReader br= new BufferedReader(fr);
     try {
         while ((sCurrentLine = br.readLine()) != null){
             stopwords[k]=sCurrentLine;
             k++;
         }
     } catch (IOException ex) {
         Logger.getLogger(KelolaApp.class.getName()).log(Level.SEVERE, null, ex);
     }
     
     wordsList.addAll(Arrays.asList(Kata));
     for(int i = 0; i < wordsList.size(); i++){
         for(int j = 0; j < k; j++){
             if(stopwords[j].contains(wordsList.get(i))){
                 wordsList.remove(i);
                 break;
             }
         }
     }
     
     StringBuilder buffer = new StringBuilder();
         boolean processedFirst = false;
         for (Iterator<String> it = wordsList.iterator(); it.hasNext();) {
             str = it.next();
             if(processedFirst) {
                 buffer.append(" ");
             }
             buffer.append(this.Stemming(str));
             processedFirst = true;
         }
         String firstParam = buffer.toString();
         
         String id = TFno.getText();
         String nama = TFNamaKel.getText();
         String kelas = CBKelas.getSelectedItem().toString();
         String konst = TFKonstKel.getText();
         String tipe = TFTipeKel.getText();
         String var = TFVarKel.getText();
         String soal = TAKel.getText();
         String foto = LblFoto.getIcon().toString();
         String query = " insert into appdb(id, nama, kelas, konst, tipe, var, kata, soal, foto) values(?,?,?,?,?,?,?,?,?)";
         PreparedStatement preparedStmt = connection.getKoneksi().prepareStatement(query);
         preparedStmt.setString(1,id);
         preparedStmt.setString(2,nama);
         preparedStmt.setString(3,kelas);
         preparedStmt.setString(4,konst);
         preparedStmt.setString(5,tipe);
         preparedStmt.setString(6,var);
         preparedStmt.setString(7,firstParam);
         preparedStmt.setString(8,soal);
         preparedStmt.setString(9,foto);
         preparedStmt.executeUpdate();
     return str;
 }
 
 //1. cek kata di db
 private boolean cek(String str) throws SQLException{
     String sql = "select * from tb_katadasar where katadasar='"+ str +"'";
     Statement st = connection.getKoneksi().createStatement();
     ResultSet rs = st.executeQuery(sql);
     if(rs.next()){
         String hsl = rs.getString("katadasar");
         System.out.print(hsl+" ");
         return true;
     }
     return false;
 }
 
// 2. Buang Infection suffixes (-lah, -kah, -ku, mu, -nya, -pun) 
 private String IS(String str) throws SQLException{
     if(this.cek(str)==false){
         if(str.matches("(\\w+)(lah|kah|ku|mu|nya|pun)")){
             Pattern p = Pattern.compile("(\\w+)(lah|kah|ku|mu|nya|pun)");
             Matcher m = p.matcher(str);
             while (m.find()) {
                 String hsl_IS= m.group(1).replace(p.pattern(), "");
                 return hsl_IS;
             }
         } 
     }
     return str;
}
 
//3. Buang Derivation suffix (-kan, -i, an) 
 private String DS(String str) throws SQLException{
     if(this.cek(str)==false){
         if(str.matches("(\\w+)(kan)")){
             Pattern p = Pattern.compile("(\\w+)(kan)");
             Matcher m = p.matcher(str);
             if (m.find()) {
                 String a = m.group(1).replace(p.pattern(), "");
                 return a;
             }
         }else if(str.matches("(\\w+)(i)")){
             Pattern p2 = Pattern.compile("(\\w+)(i)");
             Matcher m2 = p2.matcher(str);
             if (m2.find()) {
                 String b = m2.group(1).replace(p2.pattern(), "");
                 return b;
             }
         }else if(str.matches("(\\w+)(an)")){
             Pattern p3 = Pattern.compile("(\\w+)(an)");
             Matcher m3 = p3.matcher(str);
             if (m3.find()) {
                 String c = m3.group(1).replace(p3.pattern(), "");
                 return c;
             }
         }
     }
     return str;
 }
 
 // 4. Buang Derivation prefix atau awalan1 
 private String DP(String str) throws SQLException{
     if(this.cek(str)==false){
         if(str.matches("(meng|meny|men|mem|me|peng|peny|pen|pem|di|ter|ke)(\\w+)")){
             String n = str.substring(0,4);
             String m = str.substring(4,5);
             String o = str.substring(0,3);
             String p = str.substring(3,4);
             String q = str.substring(0,2);
             if("meng".equals(n)){
                 if("e".equals(m)||"u".equals(m)){
                     String hsl_DP3 = str.replace(n, "k");
                     return hsl_DP3;
                 }else{
                     String hsl_DP4 = str.replace(n, "");
                     return hsl_DP4; 
                 }
             }
             else if("meny".equals(n)){
                 String hsl_DP5 = str.replace(n, "s");
                 return hsl_DP5; 
             }
             else if("men".equals(o)){
                 String hsl_DP6 = str.replace(o, "t");
                 return hsl_DP6; 
             }
             else if("mem".equals(o)){
                 if("a".equals(p)||"i".equals(p)||"u".equals(p)||"e".equals(p)||"o".equals(p)){
                     String hsl_DP7 = str.replace(o, "p");
                     return hsl_DP7; 
                 }else{
                     String hsl_DP8 = str.replace(o, "");
                     return hsl_DP8; 
                 }
             }
             else if("me".equals(q)){
                 String hsl_DP9 = str.replace(q, "");
                 return hsl_DP9; 
             }
             else if("peng".equals(n)){
                 if("e".equals(m)||"a".equals(m)){
                     String hsl_DP10 = str.replace(m, "k");
                     return hsl_DP10; 
                 }else{
                     String hsl_DP11 = str.replace(n, "");
                     return hsl_DP11; 
                 }
             }
             else if("peny".equals(n)){
                 String hsl_DP12 = str.replace(n, "s");
                 return hsl_DP12; 
             }
             else if("pen".equals(o)){
                 if("a".equals(p)||"i".equals(p)||"u".equals(p)||"e".equals(p)||"o".equals(p)){
                     String hsl_DP13 = str.replace(o, "t");
                     return hsl_DP13; 
                 }else{
                     String hsl_DP14 = str.replace(o, "");
                     return hsl_DP14; 
                 }
             }
             else if("pem".equals(o)){
                 if("a".equals(p)||"i".equals(p)||"u".equals(p)||"e".equals(p)||"o".equals(p)){
                     String hsl_DP15 = str.replace(o, "p");
                     return hsl_DP15; 
                 }else{
                     String hsl_DP16 = str.replace(o, "");
                     return hsl_DP16; 
                 }
             }
             else if("di".equals(q)){
                 String hsl_DP17 = str.replace(q, "");
                 return hsl_DP17; 
             }
             else if("ter".equals(o)){
                 String hsl_DP17 = str.replace(o, "");
                 return hsl_DP17; 
             }
             else if("ke".equals(q)){
                 String hsl_DP17 = str.replace(q, "");
                 return hsl_DP17; 
             }
         }
     }
     return str;
 }
 
 //5. Buang second order prefiks (awalan kedua)
 private String DP2(String str) throws SQLException{
     if(this.cek(str)==false){
         if(str.matches("(ber|bel|be|per|pe|pel|se)(\\w+)")){
             String o = str.substring(0,3);
             String q = str.substring(0,2);
             if("ber".equals(o)){
                 String hsl_DP18 = str.replace(o, "");
                 return hsl_DP18; 
             }
             else if("bel".equals(o)){
                 String hsl_DP19 = str.replace(o, "");
                 return hsl_DP19; 
             }
             else if("be".equals(q)){
                 String hsl_DP20 = str.replace(q, "");
                 return hsl_DP20;
             }
             else if("per".equals(o)){
                 String hsl_DP21 = str.replace(o, "");
                 return hsl_DP21;
             }
             else if("pe".equals(q)){
                 String hsl_DP22 = str.replace(q, "");
                 return hsl_DP22; 
             }
             else if("pel".equals(o)){
                 String hsl_DP23 = str.replace(o, "");
                 return hsl_DP23; 
             }
             else if("se".equals(q)){
                 String hsl_DP24 = str.replace(q, "");
                 return hsl_DP24; 
             }
         }
     }
     return str;
 }
 
 //6. Pemanggilan Stemming
 private String Stemming(String str) throws SQLException{
    if(this.cek(str)==true){
        return str;
    }
    str = this.IS(str);
    str = this.DP(str);
    str = this.DP2(str);
    str = this.DS(str);
     return str;
 }

    private void TFVarKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFVarKelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFVarKelActionPerformed

    private void TFTipeKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTipeKelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTipeKelActionPerformed

    private void TFNamaKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNamaKelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNamaKelActionPerformed

    private void TFKonstKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFKonstKelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFKonstKelActionPerformed

    private void TAKelTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_TAKelTextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TAKelTextValueChanged

    private void TAKelInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TAKelInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TAKelInputMethodTextChanged

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed

        try {
            this.filter(str);
            JOptionPane.showMessageDialog(null,"Data disimpan!");
            new KelolaApp().show();
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(KelolaApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void TFnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnoActionPerformed

    private void BtnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImageActionPerformed
        // TODO add your handling code here:
        jfc=new JFileChooser();
        if(jfc.showOpenDialog(LblFoto)==JFileChooser.APPROVE_OPTION){
            
            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image img=toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized=img.getScaledInstance(200, 250, Image.SCALE_DEFAULT);
            ImageIcon imageIcon=new ImageIcon(imagedResized);
            
            LblFoto.setIcon(imageIcon);
            //TFjudul.setText(jfc.getSelectedFile().getName());
            
            file=new File(jfc.getSelectedFile().getPath()); // file untuk dikopi
        }
    }//GEN-LAST:event_BtnImageActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        // TODO add your handling code here:
        new TblData().show();
    }//GEN-LAST:event_BtnEditActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        // TODO add your handling code here:
        autonomor();
        TFNamaKel.setText("");
        TFKonstKel.setText("");
        TFTipeKel.setText("");
        TFVarKel.setText("");
        LblFoto.setIcon(null);
    }//GEN-LAST:event_BtnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new KelolaApp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnImage;
    private javax.swing.JButton BtnSimpan;
    public javax.swing.JComboBox CBKelas;
    private javax.swing.JLabel KonstAppKel;
    public javax.swing.JLabel LblFoto;
    private javax.swing.JLabel NamaAppKel;
    private javax.swing.JLabel NamaAppKel1;
    private javax.swing.JLabel SoalAppKel;
    public java.awt.TextArea TAKel;
    public javax.swing.JTextField TFKonstKel;
    public javax.swing.JTextField TFNamaKel;
    public javax.swing.JTextField TFTipeKel;
    public javax.swing.JTextField TFVarKel;
    public javax.swing.JTextField TFno;
    private javax.swing.JLabel TipeAppKel;
    private javax.swing.JLabel VarAppKel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
